<?php
/**
* Data file generated by EMBFileMenu (ArrayModel)
* Date: July 19, 2014, 12:13 pm
*
* Allowed data structure:
*   array(
*       'menuid' => 'menuid',
*       'titles' => 'titles',
*       'descriptions' => 'descriptions',
*       'descriptionashint' => 'descriptionashint',
*       'visible' => 'visible',
*       'locked' => 'locked',
*       'sortposition' => 'sortposition',
*       'maxdepth' => 'maxdepth',
*       'icon' => 'icon',
*       'nestedconfig' => 'nestedconfig',
*       'userroles' => 'userroles',
*       'scenarios' => 'scenarios',
*       'adminroles' => 'adminroles',
*       'created' => 'created',
*       'createduser' => 'createduser',
*       'modified' => 'modified',
*       'modifieduser' => 'modifieduser',
*   )
*/
return array(
	0 => array(
		'menuid' => 'main',
		'titles' => array(
			'hu' => 'Menu',
		),
		'descriptionashint' => true,
		'visible' => true,
		'sortposition' => 0,
		'icon' => '',
		'nestedconfig' => '[{"id":"807c521b3fecc2a77175c32a557e317b"},{"id":"988f8ba38a9ad2ca1ad281634b159729"},{"id":"a0ecbcc5999d3add213e67976d0b9e8e"},{"id":"344c0fad2e62c393187c7b7ad19dd55e"},{"id":"775d37ec854c0ee2acdc99132b8cf48b"},{"id":"18c87762f62d440095693cab6914b625"}]',
		'userroles' => '',
		'scenarios' => '',
		'adminroles' => '',
		'modified' => '2014.07.19. 12:13:54',
		'modifieduser' => 'admin',
	),
);
